name: bangapp
description: social media application in tanzania

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html

version: 1.0.0+38

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  bloc: ^8.1.0
  animations: ^2.0.7
  ionicons: ^0.2.2
  carousel_slider: ^4.2.1
  cached_network_image: ^3.2.2
  cupertino_icons: ^1.0.2
  shimmer: ^2.0.0
  cloud_firestore: ^4.5.2
  curved_navigation_bar: ^1.0.1
  dropdown_button2: ^2.1.0
  file_picker: ^5.2.10
  flutter:
    sdk: flutter
  loading_overlay: ^0.3.0
  flutter_svg: ^2.0.5
  font_awesome_flutter: ^10.4.0
  image_picker: ^0.8.4+1
  like_button: ^2.0.2
  modal_progress_hud_nsn: ^0.4.0
  path_provider: ^2.0.9
  provider: ^6.0.0
  story_view: ^0.14.0
  flutter_spinkit: ^5.0.0
  toast: ^0.3.0
  http: ^0.13.5
  chewie: ^1.7.1
  video_player: ^2.7.2
  photo_manager: 2.6.0
  image_cropper: ^4.0.1
  image_editor: ^1.2.1
  image_editor_plus: ^0.2.0
  video_editor: ^3.0.0
  fraction: ^4.1.4
  ffmpeg_kit_flutter_min: ^5.1.0
  fluttertoast: ^8.2.2
  mime: ^1.0.4
  firebase_messaging: ^14.6.5
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.1
  flutter_local_notifications: ^15.1.0+1
  filter_list: ^1.0.2
  flutter_keyboard_visibility: ^5.4.1
  infinite_scroll_pagination: ^3.2.0
  socket_io_client: ^2.0.3+1
  web_socket_channel: any
  visibility_detector: ^0.4.0+2
  comment_box: ^0.0.18
  shared_preferences: ^2.2.1
  flutter_share: ^2.0.0
  screenshot: ^2.1.0
  receive_sharing_intent: ^1.4.5
  appinio_video_player: ^1.2.2
  flutter_chat_ui: ^1.6.9
  open_filex: ^4.3.4
  google_fonts: ^4.0.4
  read_more_text: ^0.0.5
  emoji_regex: ^0.0.5
  timeago: ^3.5.0
  onesignal_flutter: ^5.0.2
  google_sign_in: ^6.1.5
  date_format: ^2.0.7
  date_formatter: ^0.0.4
  video_box: ^0.17.0
  flutter_bloc: ^8.1.3
  flutter_cache_manager: ^3.3.1
  dio: ^5.3.3
  preload_page_view: ^0.2.0
  flutter_image_compress: ^2.1.0
  video_compress: ^3.1.2
  flutter_native_image: ^0.0.6
  flutter_hooks: ^0.20.5
  light_compressor: ^2.2.0
  skeletonizer: ^1.0.1
  loading_animation_widget: ^1.2.1
  sizer: ^2.0.15
  get_storage: ^2.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: any
  permission_handler: any


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: 'assets/images/app_icon.jpg'

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/
    - images/
  fonts:
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf
    - family: SourceSansPro
      fonts:
        - asset: fonts/SourceSansPro-Regular.ttf
        - asset: fonts/SourceSansPro-Italic.ttf
          style: italic
        - asset: fonts/SourceSansPro-Light.ttf
          weight: 100
        - asset: fonts/SourceSansPro-SemiBold.ttf
          weight: 700
    - family: Billabong
      fonts:
        - asset: fonts/FontsFree-Net-Billabong.ttf
    - family: Metropolis
      fonts:
        - asset: fonts/Metropolis-Regular.otf
    #- asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
